# Cellular Automata

Cellular Automaton is model of computation in auto mata thoery. Cellular automata is used in various area, including physics, theoretical biology and microstructure modeling. 

In cellular automaton, it consists of a regular grid of cell, and there are only two finite state, on and off. 

We consider 1 as on and 0 as off.

All cells will be defined relative to the neiborhood cells. 

<Cellular automaton, Wikipedia, https://en.wikipedia.org/wiki/Cellular_automaton>

# Conway's Game of Life
There are 4 rules in Conway's Game of Life.

-1. Any live cell with fewer than two live neighbours dies, as if by underpopulation.

-2. Any live cell with two or three live neighbours lives on to the next generation.

-3. Any live cell with more than three live neighbours dies, as if by overpopulation.

-4. Any dead cell with exactly three live neighbours becomes a live cell, as if by reproduction.

<Conway's Game of Life, Wikipedia, https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life>

Acutally, this technique processing neighbor cells will be usefully used in Ising Model.


In [27]:
import math, random
import numpy as np


def conway_life_game(matrix_init):
    temp_matrix = np.zeros([n,n])
    # doing conway_life_game in all coordinates existed in matrix
    for x in range(n):
        for y in range(n):
            top = matrix_init[(y-1)%n, x]
            bottom = matrix_init[(y+1)%n, x]
            right = matrix_init[y, (x+1)%n]
            left = matrix_init[y, (x-1)%n]
            top_left = matrix_init[(y-1)%n, (x-1)%n]
            top_right = matrix_init[(y-1)%n, (x+1)%n]
            bottom_left = matrix_init[(y+1)%n, (x-1)%n]
            bottom_right = matrix_init[(y+1)%n, (x+1)%n]

            # Add 8 directions' value
            Total = top + bottom + right + left + top_left + top_right + bottom_left + bottom_right

            # if main cell is alive and total value of all neighborhood cell is 2 or 3, main cell will be still alive.
            if temp_matrix[y, x] == 1 and Total == (2 or 3):
                temp_matrix[y, x] = 1
            
            # if main cell is dying and total value of all neighborhood cell is 3, main cell will be live again.
            elif temp_matrix[y,x] ==0 and Total == 3:
                temp_matrix[y,x] =1
            
            #Else, main cell gonna die.
            else:
                temp_matrix[y, x] = 0
    
    return temp_matrix

# n is matrix size
n = 5 

matrix_init = np.zeros([n,n])
matrix_init = np.random.choice([0,1], size=(n,n))
matrix_result = matrix_init

# gen_num is number how much we repeat and make generation. 
gen_num = 3
for i in range(gen_num):
    matrix_result = conway_life_game(matrix_result)

print(matrix_result)



[[0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 1.]
 [1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 1.]]
[[0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 1.]]
[[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
